# Site settings
title: Cascading Treesheets
email: eob@csail.mit.edu
description: > # this means to ignore newlines until "baseurl:"
  Cascading Treesheets (CTS) is an open source web language that does 
  for web structure what CSS does for style. It allows you to slice, dice, and 
  combine web content from different sources.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://treesheets.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
